### ISSUE TITLE
ovs remove nodes failed!

### ISSUE THREAD

**Issue by deepshirsath** [openvstorage/framework-alba-plugin#173]
Open vStorage: 2.7.1-rev.3796.b423743-1
Open vStorage - Backend: 1.7.1-rev.660.c655e82-1
Open vStorage - SDM: 1.6.1-rev.327.9490bc3-1
Storage Driver - Base: 6.0.3-dev.201607191821.0758481
Storage Driver - Server: 6.0.3-dev.201607191821.0758481
Alba: 0.9.14
Arakoon 1.9.8

Executed 'ovs remove nodes' for removing 3rd node from 3 node ovs cluster but it has failed.

root@ubuntu1:~# ovs remove nodes 192.168.10.203

+++ Remove nodes started +++

WARNING: Some of these steps may take a very long time, please check the logs for more logging information

Following nodes with IPs will be removed from the cluster: ['192.168.10.203']
Creating SSH connections to remaining master nodes
  Node with IP 192.168.10.201  successfully connected to
  Node with IP 192.168.10.202  successfully connected to
  Node with IP 192.168.10.203  successfully connected to
Starting removal of nodes
  Cleaning up node with IP 192.168.10.203
    Removing vPool pool1 from node

+++ Demoting node +++

Leaving Arakoon ovsdb cluster
Leaving Etcd cluster
Update configurations
Restarting master node services
Removing/unconfiguring RabbitMQ
  [192.168.10.203] rabbitmq-server already halted
Removing services
Removing service memcached
  [192.168.10.203] memcached stopped
Removing service rabbitmq-server
  [192.168.10.203] rabbitmq-server already halted
Removing service scheduled-tasks
  [192.168.10.203] scheduled-tasks stopped
Removing service snmp
  [192.168.10.203] snmp stopped
Removing service webapp-api
  [192.168.10.203] webapp-api stopped
Removing service volumerouter-consumer
  [192.168.10.203] volumerouter-consumer stopped
Update existing vPools
Restarting services
  [192.168.10.201] watcher-framework stopped
  [192.168.10.202] watcher-framework stopped
  [192.168.10.203] watcher-framework stopped
  [192.168.10.201] memcached restarted
  [192.168.10.202] memcached restarted
  [192.168.10.201] watcher-framework started
  [192.168.10.202] watcher-framework started
  [192.168.10.203] watcher-framework started

+++ Running "demote" hooks +++

Update existing vPools
Restarting services
  [192.168.10.201] watcher-framework stopped
  [192.168.10.202] watcher-framework stopped
  [192.168.10.203] watcher-framework stopped
  [192.168.10.201] memcached restarted
  [192.168.10.202] memcached restarted
  [192.168.10.201] watcher-framework started
  [192.168.10.202] watcher-framework started
  [192.168.10.203] watcher-framework started
Avahi installed

+++ Announcing service +++

  [192.168.10.203] avahi-daemon restarted
Demote complete
    Removing node from model

+++ Running "remove" hooks +++

+++++++++++++++++++++++++++++++++++++++
+++  An unexpected error occurred:  +++
+++  'critical'                     +++
+++++++++++++++++++++++++++++++++++++++
root@ubuntu1:~#

lib.log of node 1

> 2016-08-02 20:58:14 91500 +0530 - ubuntu1 - 106117/139813639006016 - lib/setup - 267 - INFO - Running "remove" hooks
2016-08-02 20:58:15 54700 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 268 - INFO - Ensure single CHAINED mode - ID 1470151695_6TR5xpRmSH - Setting initial value for key ovs_ensure_single_albanode.remove_asd
2016-08-02 20:58:15 75600 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 269 - INFO - Ensure single CHAINED mode - ID 1470151695_6TR5xpRmSH - New task albanode.remove_asd with params {'node_guid': u'4a04b5d8-849e-4d05-b935-a950047f2e9b', 'expected_safety': {}, 'asd_id': u'HKapxIuxfT8tMiqGFtavxLmHWBr1LX2S'} scheduled for execution
2016-08-02 20:58:15 95100 +0530 - ubuntu1 - 106117/139813639006016 - lib/albanode - 270 - DEBUG - Removing ASD HKapxIuxfT8tMiqGFtavxLmHWBr1LX2S at node 192.168.10.203
2016-08-02 20:58:21 46900 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 275 - INFO - Ensure single CHAINED mode - ID 1470151701_OmHnFBsgtJ - Setting initial value for key ovs_ensure_single_ovs.disk.sync_with_reality
2016-08-02 20:58:21 66800 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 276 - INFO - Ensure single CHAINED mode - ID 1470151701_OmHnFBsgtJ - New task ovs.disk.sync_with_reality with params {'storagerouter_guid': u'e382a2dd-54be-4115-9453-08a633773168'} scheduled for execution
2016-08-02 20:58:32 48600 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 277 - INFO - Ensure single CHAINED mode - ID 1470151701_OmHnFBsgtJ - Task ovs.disk.sync_with_reality finished successfully
2016-08-02 20:58:32 48700 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 278 - INFO - Ensure single CHAINED mode - ID 1470151701_OmHnFBsgtJ - Setting initial value for key ovs_ensure_single_ovs.disk.sync_with_reality
2016-08-02 20:58:32 69200 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 279 - INFO - Ensure single CHAINED mode - ID 1470151695_6TR5xpRmSH - Task albanode.remove_asd finished successfully
2016-08-02 20:58:32 69300 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 280 - INFO - Ensure single CHAINED mode - ID 1470151695_6TR5xpRmSH - Setting initial value for key ovs_ensure_single_albanode.remove_asd
2016-08-02 20:58:32 92500 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 281 - INFO - Ensure single CHAINED mode - ID 1470151712_bWZ9SpGyd1 - Setting initial value for key ovs_ensure_single_albanode.remove_disk
2016-08-02 20:58:33 11200 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 282 - INFO - Ensure single CHAINED mode - ID 1470151712_bWZ9SpGyd1 - New task albanode.remove_disk with params {'node_guid': u'4a04b5d8-849e-4d05-b935-a950047f2e9b', 'disk': u'ata-WDC_WD1002FBYS-02A6B0_WD-WMATV6674000'} scheduled for execution
2016-08-02 20:58:35 70800 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 286 - INFO - Ensure single CHAINED mode - ID 1470151715_P1zWaaCj4Y - New task ovs.disk.sync_with_reality with params {'storagerouter_guid': u'e382a2dd-54be-4115-9453-08a633773168'} scheduled for execution
2016-08-02 20:58:46 56800 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 287 - INFO - Ensure single CHAINED mode - ID 1470151715_P1zWaaCj4Y - Task ovs.disk.sync_with_reality finished successfully
2016-08-02 20:58:46 74400 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 288 - INFO - Ensure single CHAINED mode - ID 1470151712_bWZ9SpGyd1 - Task albanode.remove_disk finished successfully
2016-08-02 20:58:46 94400 +0530 - ubuntu1 - 106117/139813639006016 - lib/scheduled tasks - 289 - INFO - Ensure single CHAINED mode - ID 1470151726_y7fkz2058H - New task albanode.remove_asd with params {'node_guid': u'4a04b5d8-849e-4d05-b935-a950047f2e9b', 'expected_safety': {}, 'asd_id': u'dGeoQn8hDAwmVStPnj7jhZQrPeRyWw5F'} scheduled for execution
2016-08-02 20:58:47 07400 +0530 - ubuntu1 - 106117/139813639006016 - lib/albanode - 290 - DEBUG - Removing ASD dGeoQn8hDAwmVStPnj7jhZQrPeRyWw5F at node 192.168.10.203
2016-08-02 20:58:47 50000 +0530 - ubuntu1 - 106117/139813639006016 - lib/setup - 291 - INFO -

2016-08-02 20:58:47 50100 +0530 - ubuntu1 - 106117/139813639006016 - lib/setup - 292 - ERROR - An unexpected error occurred:
Traceback (most recent call last):
  File "ovs/lib/setup.py", line 703, in remove_nodes
    SetupController._run_hooks('remove', storage_router.ip)
  File "ovs/lib/setup.py", line 1653, in _run_hooks
    function(cluster_ip=cluster_ip, **kwargs)
  File "ovs/lib/helpers/..//albacontroller.py", line 712, in on_remove
    AlbaNodeController.remove_asd(node_guid=osd.alba_disk.alba_node_guid, asd_id=osd.osd_id, expected_safety={})
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "ovs/lib/helpers/..//albanodecontroller.py", line 236, in remove_asd
    if (safety_crit != 0 or safety_lost != 0) and (safety_crit != expected_safety['critical'] or safety_lost != expected_safety['lost']):
KeyError: 'critical'
2016-08-02 20:58:47 50100 +0530 - ubuntu1 - 106117/139813639006016 - lib/setup - 293 - ERROR - 'critical'
Traceback (most recent call last):
  File "ovs/lib/setup.py", line 703, in remove_nodes
    SetupController._run_hooks('remove', storage_router.ip)
  File "ovs/lib/setup.py", line 1653, in _run_hooks
    function(cluster_ip=cluster_ip, **kwargs)
  File "ovs/lib/helpers/..//albacontroller.py", line 712, in on_remove
    AlbaNodeController.remove_asd(node_guid=osd.alba_disk.alba_node_guid, asd_id=osd.osd_id, expected_safety={})
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "ovs/lib/helpers/..//albanodecontroller.py", line 236, in remove_asd
    if (safety_crit != 0 or safety_lost != 0) and (safety_crit != expected_safety['critical'] or safety_lost != expected_safety['lost']):
KeyError: 'critical' 

> 

![after-remove-nodes-command-failed](https://cloud.githubusercontent.com/assets/14201912/17336283/1b2b1888-58fb-11e6-9504-7e5928fdef9a.PNG)
![ovs-remove-nodes](https://cloud.githubusercontent.com/assets/14201912/17336284/1b2b765c-58fb-11e6-8883-1e3775dece10.PNG)
[lib.log.docx](https://github.com/openvstorage/framework-alba-plugin/files/397550/lib.log.docx)

**Comment by khenderick** [comment]
Fixed by #186 in openvstorage-backend-1.7.2-rev.675.37ca5b8

**Comment by JeffreyDevloo** [comment]
This issue has been fixed in openvstorage-backend-1.7.2-rev.675.37ca5b8. Could no longer reproduce this issue.
