### ISSUE TITLE
KeyError: 'local_summary' in dal.log when loading backend info

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework-alba-plugin#187]
```
2016-08-10 14:51:59 44300 +0200 - ctrl-roub-01 - 138833/140567073769216 - dal/albabackend - 135 - ERROR - Collecting remote ALBA backend information failed with error: 'local_summary'
Traceback (most recent call last):
  File "ovs/dal/hybrids/albabackend.py", line 454, in _load_backend_info
    return_value[_alba_backend_guid].update(info['local_summary'])
KeyError: 'local_summary'
2016-08-10 15:03:00 96500 +0200 - ctrl-roub-01 - 145924/140336017950464 - dal/albabackend - 133 - ERROR - Collecting remote ALBA backend information failed with error: 'local_summary'
Traceback (most recent call last):
  File "ovs/dal/hybrids/albabackend.py", line 454, in _load_backend_info
    return_value[_alba_backend_guid].update(info['local_summary'])
KeyError: 'local_summary'
2016-08-10 15:03:00 96700 +0200 - ctrl-roub-01 - 145924/140335506257664 - dal/albabackend - 134 - ERROR - Collecting remote ALBA backend information failed with error: 'local_summary'
Traceback (most recent call last):
  File "ovs/dal/hybrids/albabackend.py", line 454, in _load_backend_info
    return_value[_alba_backend_guid].update(info['local_summary'])
KeyError: 'local_summary'
```

This is also accompanied by red balls in the detail page of the global backend on OVH.

Version: 2.7.1-fargo.2-1

**Comment by khenderick** [comment]
Fixed by openvstorage/framework#808, packaged in openvstorage-2.7.2-rev.3865.5388319 & openvstorage-2.7.1-fargo.3

**Comment by khenderick** [comment]
For QA validation: The issue was not related to backends, but to the fact that a cached API client did not re-login when it's cached token was expired.

**Comment by kinvaris** [comment]
PASSED: Acquired bearer token, bearer token expired, retried call, got 401.
