### ISSUE TITLE
albanode.initialize_disk during initialization of the disks

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework-alba-plugin#188]
2.7.1-fargo.2-1

Following error during initialization of the disks:

```
2016-08-12 17:03:39 23100 +0200 - stor-01.be-g8-3 - 2065/140323643111232 - celery/celery.worker.job - 200 - ERROR - Task albanode.initialize_disk[05948655-58be-4e2c-991d-a99d4d2cd3d1] raised unexpected: ReadTimeout(ReadTimeoutError('None: None',),)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 119, in initialize_disks
    result = node.client.add_disk(disk_id)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 101, in add_disk
    return self._call(requests.post, 'disks/{0}/add'.format(disk_id), timeout=60)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 56, in _call
    response = method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: None: None
```

**Comment by JeffreyDevloo** [comment]
### Information
We have not encountered this sort of error anymore on our automated testing environments.
