### ISSUE TITLE
albanode.remove_disk error while removing a disk

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework-alba-plugin#189]
2.7.1-fargo.2-1

Error while removing a disk in the GUI:

```
2016-08-12 17:16:58 57200 +0200 - stor-01.be-g8-3 - 2065/140323643111232 - celery/celery.worker.job - 264 - ERROR - Task albanode.remove_disk[d5939c68-bbf4-4c85-8610-31675286f09d] raised unexpected: RuntimeError('Disk ata-WDC_WD10EALS-002BA0_WD-WCATR1238791 not available on node d17dc6e0-f6de-47d9-88b4-22f76baa9264',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 157, in remove_disk
    raise RuntimeError('Disk {0} not available on node {1}'.format(disk, node.guid))
RuntimeError: Disk ata-WDC_WD10EALS-002BA0_WD-WCATR1238791 not available on node d17dc6e0-f6de-47d9-88b4-22f76baa9264
```

**Comment by kvanhijf** [comment]
Most likely fixed by https://github.com/openvstorage/framework/issues/792

**Comment by wimpers** [comment]
Closed by PM.
