### ISSUE TITLE
Initializing disk succeeded but add asds disagrees

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework-alba-plugin#253]
As seen on one of our CI environments: 

```
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51 44300 +0200 - ovs-node01-1604 - 8011/140238963914496 - asd-manager/werkzeug - 11 - INFO - 10.100.199.171 - - [26/Oct/2016 22:14:51] "GET /disks HTTP/1.1" 200 -
Oct 26 22:14:51 ovs-node01-1604 celery[10732]: 2016-10-26 22:14:51 44500 +0200 - ovs-node01-1604 - 10780/140525619275520 - lib/albanode - 132 - DEBUG - Initializing disk ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8 at node 10.100.199.171
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51 46600 +0200 - ovs-node01-1604 - 8011/140238963914496 - asd-manager/api - 12 - INFO - Add disk /dev/disk/by-id/ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51 46600 +0200 - ovs-node01-1604 - 8011/140238963914496 - asd-manager/disk - 13 - INFO - Preparing disk /dev/disk/by-id/ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51 46700 +0200 - ovs-node01-1604 - 8011/140238963914496 - asd-manager/disk - 14 - INFO - Scanning controllers
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51 47100 +0200 - ovs-node01-1604 - 8011/140238963914496 - asd-manager/disk - 15 - INFO - Scan complete
Oct 26 22:14:51 ovs-node01-1604 python[8011]: umount: /mnt/alba-asd/feuyAhc0f7Cz7YyD: mountpoint not found
Oct 26 22:14:51 ovs-node01-1604 kernel: [  877.236810]  sdf:
Oct 26 22:14:51 ovs-node01-1604 python[8011]: Warning: failed to translate partition name
Oct 26 22:14:51 ovs-node01-1604 kernel: [  877.287796]  sdf: sdf1
Oct 26 22:14:51 ovs-node01-1604 kernel: [  877.324085]  sdf: sdf1
Oct 26 22:14:51 ovs-node01-1604 kernel: [  877.438998] XFS (sdf1): Mounting V5 Filesystem
Oct 26 22:14:51 ovs-node01-1604 kernel: [  877.446928] XFS (sdf1): Ending clean mount
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51 72500 +0200 - ovs-node01-1604 - 8011/140238963914496 - asd-manager/disk - 16 - INFO - Prepare disk /dev/disk/by-id/ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8 complete
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51 75100 +0200 - ovs-node01-1604 - 8011/140238963914496 - asd-manager/werkzeug - 17 - INFO - 10.100.199.171 - - [26/Oct/2016 22:14:51] "POST /disks/ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8/add HTTP/1.1" 200 -
Oct 26 22:14:51 ovs-node01-1604 python[8011]: Traceback (most recent call last):
Oct 26 22:14:51 ovs-node01-1604 python[8011]:   File "/opt/asd-manager/source/app/decorators.py", line 73, in new_function
Oct 26 22:14:51 ovs-node01-1604 python[8011]:     return_data = f(*args, **kwargs)
Oct 26 22:14:51 ovs-node01-1604 python[8011]:   File "/opt/asd-manager/source/app/api.py", line 198, in add_asd_disk
Oct 26 22:14:51 ovs-node01-1604 python[8011]:     raise BadRequest('Disk {0} is not yet initialized'.format(disk_data['aliases'][0]))
Oct 26 22:14:51 ovs-node01-1604 python[8011]: BadRequest: Disk /dev/disk/by-id/ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8 is not yet initialized
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51.804842 - None
Oct 26 22:14:51 ovs-node01-1604 python[8011]: 2016-10-26 22:14:51 80600 +0200 - ovs-node01-1604 - 8011/140238963914496 - asd-manager/werkzeug - 18 - INFO - 10.100.199.171 - - [26/Oct/2016 22:14:51] "POST /disks/ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8/asds HTTP/1.1" 400 -
Oct 26 22:14:51 ovs-node01-1604 celery[10732]: 2016-10-26 22:14:51 81300 +0200 - ovs-node01-1604 - 10732/140525619275520 - celery/celery.worker.job - 99 - ERROR - Task albanode.initialize_disk[e7e62b04-168d-49c1-afcc-c7d30f8e1845] raised unexpected: RuntimeError(u'Disk /dev/disk/by-id/ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8 is not yet initialized',)
Oct 26 22:14:51 ovs-node01-1604 celery[10732]: Traceback (most recent call last):
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:     R = retval = fun(*args, **kwargs)
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:     return self.run(*args, **kwargs)
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:   File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 165, in initialize_disks
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:     add_asd_result = node.client.add_asd(disk_id=device_id)
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:   File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 175, in add_asd
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:     return self._call(requests.post, 'disks/{0}/asds'.format(disk_id), timeout=30)
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:   File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 97, in _call
Oct 26 22:14:51 ovs-node01-1604 celery[10732]:     raise RuntimeError(error_message)
Oct 26 22:14:51 ovs-node01-1604 celery[10732]: RuntimeError: Disk /dev/disk/by-id/ata-QEMU_HARDDISK_4fe53c0c-95f5-11e6-8 is not yet initialized
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/alba-asdmanager/pull/137 --> openvstorage-sdm-1.6.4-rev.400.f51c4e2

**Comment by kvanhijf** [comment]
@QA: Was only an issue on Ubuntu 16.04 and should not always have occurred, dependent on speed of hardware / software. Should no longer re-occur since we now implemented a proper way to wait for the partitions to have been created
