### ISSUE TITLE
[Active Drive] Handle custom slot ids

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#481]
### Problem description
The current free slot the fwk generates is based on the previous slots for sorting purposes.
We should discard the sorting if a custom one is introduced.

The current exception:
```
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]: 2017-09-19 10:09:11 22700 +0200 - ovs-node01-1604 - 32531/139893280480624 - api/middleware.py - 3294 - ERROR - An unhandled exception occurred: invalid literal for int() with base 10
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]: Traceback (most recent call last):
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/usr/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 78, in view
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     return self.dispatch(request, *args, **kwargs)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     return view_func(*args, **kwargs)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 399, in dispatch
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     response = self.handle_exception(exc)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 396, in dispatch
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     response = handler(request, *args, **kwargs)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 87, in new_function
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     result = f(*args, **kw)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 484, in new_function
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     result = f(*args, **kwargs)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 229, in new_function
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     result = f(args[0], **new_kwargs)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/opt/OpenvStorage/webapps/api/backend/views/albanodes.py", line 201, in generate_empty_slot
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     return AlbaNodeController.generate_empty_slot(albanode.guid)
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:   File "/opt/OpenvStorage/ovs/lib/albanode.py", line 156, in generate_empty_slot
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]:     if int(prefix) > highest_prefix_count:
Sep 19 10:09:11 ovs-node01-1604 gunicorn[32493]: ValueError: invalid literal for int() with base 10: '0c'
```

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework-alba-plugin/pull/486
