### ISSUE TITLE
ReadTimeout when attempting to remove ASD via GUI

### ISSUE THREAD

**Issue by ThoMeyM** [openvstorage/framework-alba-plugin#520]
2017-11-09 10:30:40 89600 +0100 - pocops-voldrv01 - 1684/140547671979776 - celery/celery.worker.job - 77273 - ERROR - Task albanode.reset_asd[3238c3c5-3691-4439-93e9-77c9da23e21e] raised unexpected: ReadTimeout(
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanode.py", line 368, in reset_asd
    expected_safety=expected_safety)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 461, in new_function
    output = f(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanode.py", line 322, in remove_asd
    for device_info in node.client.get_disks().itervalues():
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 137, in get_disks
    return self._call(requests.get, 'disks', clean=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 95, in _call
    response = method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: None: None

**Comment by wimpers** [comment]
@ovstmoens is there a workaround?

**Comment by ovstmoens** [comment]
@wimpers The workaround we used was to remove the directory first via CLI and then remove the ASD in the GUI.

**Comment by simonOpenV** [comment]
This ticket seems to be no longer relevant in the current develop code: changes have been made in the ```  remove_asd``` (now ``` remove_osd ```)
- The call ``` node.client.get_disks ``` is no longer used in the remove_osd code
- Concerning the touch command in the asd-manager which caused the timeout through an error raise: this code is not executed in the current develop in ``` GET ``` calls and should therefore not occur, even with full disks.
@JeffreyDevloo , any thoughts?

**Comment by JeffreyDevloo** [comment]
This bug is most likely still present.
