### ISSUE TITLE
Removing albanodes not working

### ISSUE THREAD

**Issue by simonOpenV** [openvstorage/framework-alba-plugin#558]
Noticed this first on my own environment, confirmed on 199.191

_What?_
AlbaNode is not removable when it should be, namely when all osds are unclaimed.

_Evidence_
 
![screenshot from 2018-01-30 10-00-17](https://user-images.githubusercontent.com/33058909/35557289-f5c0f18c-05a4-11e8-9f65-93ba37225375.png)

Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
File "/opt/OpenvStorage/ovs/lib/albanode.py", line 109, in remove_node
AlbaNodeController.remove_slot(node_guid=node.guid, slot_id=slot_id)
File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
  return self._get_current_object()(*a, **kw)
File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
   return orig(self, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
   return self.run(*args, **kwargs)
File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 461, in new_function
     output = f(*args, **kwargs)
File "/opt/OpenvStorage/ovs/lib/albanode.py", line 237, in remove_slot
  node.client.clear_slot(slot_id)
File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 182, in clear_slot
    return self._call(requests.delete, 'slots/{0}'.format(slot_id))
File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 89, in _call
   raise RuntimeError(error_message)
RuntimeError: Status code: 406 - Error: disk_not_configured'.

**Comment by simonOpenV** [comment]
This issue might have been caused by an error present in my environment at that time. 
Further research will tell.

**Comment by simonOpenV** [comment]
Fixed by #568 and asd-manager: https://github.com/openvstorage/alba-asdmanager/pull/319

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.11.2
