### ISSUE TITLE
No slots found on the backend page

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework-alba-plugin#574]
# Problem

![image](https://user-images.githubusercontent.com/2900612/36476826-47f97dbe-16ff-11e8-8246-22965bcb451b.png)

# Logs
Looks like the timeout to retrieve the stack are to optimistic.

```
In [3]: an._stack()
2018-02-21 10:54:29 57700 +0000 - R25U19 - 30226/140593082377984 - hybrids/albanode.py - 0 - ERROR - Unable to retrieve remote stack
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/dal/hybrids/albanode.py", line 128, in _stack
    remote_stack = self.client.get_stack()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 129, in get_stack
    data = self._call(requests.get, 'slots', timeout=5, clean=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 88, in _call
    response = method(**kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='10.0.11.8', port=8500): Read timed out. (read timeout=5)
Out[3]: {}

```

# Solution
Changing the timeout from 5 secs to 60 secs solved the problem:
/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py
```
            data = self._call(requests.get, 'slots', timeout=60, clean=True)
        data = self._call(method=requests.get, url='disks', timeout=60, clean=True)

```

# Version
```
ii  openvstorage                         2.10.0-dev.1505391680.bada816-1            amd64        OpenvStorage
```

**Comment by JeffreyDevloo** [comment]
Can be solved with https://github.com/openvstorage/framework-alba-plugin/pull/559. The timeout can be set in config management

**Comment by wimpers** [comment]
Released in https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.12.0
Packaged in openvstorage-backend-core_1.12.0-1_amd64.deb
