### ISSUE TITLE
Sync with reality for asds

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework-alba-plugin#577]
# Problem
Removing of an asd via the gui failed due to the api timeout.
The asd has been removed on the asd-manager but the framework is not aware of this.
A retry of removing the asd will clean up the leftovers in the framework.

It would be better if we have a sync with reality call to sync the framework with the current state of the asds.

# Logs

celery
```
Mar  9 04:18:55 NY1SRV0022 celery[14113]: 2018-03-09 04:18:55 80900 -0500 - NY1SRV0022 - 13280/140008816981760 - lib/ensure single - 97784 - INFO - Ensure single CHAINED mode - ID 1520587074_y5FNA1604w - Task albanode.remove_asd with params {'node_guid': '1a2338c3-12a3-4e7d-9fdb-14b65a0880fd', 'expected_safety': {u'good': 0, u'critical': 0, u'lost': 1047}, 'asd_id': u'wGfPBY19rD28V47vQ9PNNKFf5BxaVRBn'} had to wait 61 seconds before being able to start

Mar  9 04:20:08 NY1SRV0022 celery[14113]: 2018-03-09 04:20:08 26900 -0500 - NY1SRV0022 - 14113/140008816981760 - celery/celery.worker.job - 97795 - ERROR - Task albanode.reset_asd[6f4c3909-de4d-4535-91d3-9b8da843c2d6] raised unexpected: ReadTimeout(ReadTimeoutError('None: None',),)
Mar  9 04:20:08 NY1SRV0022 celery[14113]: Traceback (most recent call last):
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     R = retval = fun(*args, **kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     return self.run(*args, **kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/opt/OpenvStorage/ovs/lib/albanode.py", line 368, in reset_asd
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     expected_safety=expected_safety)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     return self._get_current_object()(*a, **kw)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     return orig(self, *args, **kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     return self.run(*args, **kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 461, in new_function
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     output = f(*args, **kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/opt/OpenvStorage/ovs/lib/albanode.py", line 326, in remove_asd
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     asd_id=asd_id)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 226, in delete_asd
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     return self._call(requests.post, 'disks/{0}/asds/{1}/delete'.format(disk_id, asd_id), timeout=60)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 95, in _call
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     response = method(**kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 107, in post
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     return request('post', url, data=data, json=json, **kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     return session.request(method=method, url=url, **kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     resp = self.send(prep, **send_kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     r = adapter.send(request, **kwargs)
Mar  9 04:20:08 NY1SRV0022 celery[14113]:   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 449, in send
Mar  9 04:20:08 NY1SRV0022 celery[14113]:     raise ReadTimeout(e, request=request)
Mar  9 04:20:08 NY1SRV0022 celery[14113]: ReadTimeout: None: None
```

asd-manager
```
2018-03-09 04:22:15 51600 -0500 - NY1SRV0116 - 4918/140636982626048 - asd-manager/api - 741363 - INFO - POST /disks/<disk_id>/asds/<asd_id>/delete - Entering with [] {"asd_id": "wGfPBY19rD28V47vQ9PNNKFf5BxaVRBn", "disk_id": "scsi-35001173100fa762c"}
```

**Comment by wimpers** [comment]
We probably could use this also in case of active drives

**Comment by toolslive** [comment]
it also means that some alba cli commands are taboo for everything but the framework.

**Comment by wimpers** [comment]
When implementing this we could also check https://github.com/openvstorage/framework/issues/2143 as the scheduled sync (once every hour) could retrieve the updated ABM info.

**Comment by sjovdnbos** [comment]
### Fixed by:
https://github.com/openvstorage/framework-alba-plugin/pull/629
### Package info:
openvstorage-backend-1.13.3-dev.1542964970.d80e34d
