### ISSUE TITLE
SDM migration code issue

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#578]
### Problem description
Upgraded from Bighorn-rc-2 to the latest fwk-develop

Plugin related stack:
```
2018-03-22 15:11:58 10000 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 46 - INFO - Preparing out of band migrations for SDM...
2018-03-22 15:11:58 10600 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 47 - INFO - Executing post-update migration code for ALBA Node lwVUjNgvKeYNmSX2
2018-03-22 15:11:58 14100 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 48 - ERROR - Executing post-update migration code for ALBA Node lwVUjNgvKeYNmSX2 failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 239, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 91, in _call
    raise RuntimeError(error_message)
RuntimeError: UNIQUE constraint failed: setting.code
2018-03-22 15:11:58 14600 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 49 - INFO - Executing post-update migration code for ALBA Node 5jPSR27MDD0wIu3m
2018-03-22 15:11:58 18200 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 50 - ERROR - Executing post-update migration code for ALBA Node 5jPSR27MDD0wIu3m failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 239, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 91, in _call
    raise RuntimeError(error_message)
RuntimeError: UNIQUE constraint failed: setting.code
2018-03-22 15:11:58 18700 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 51 - INFO - Executing post-update migration code for ALBA Node GjTGwgSCulp7Fluc
2018-03-22 15:11:58 22000 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 52 - ERROR - Executing post-update migration code for ALBA Node GjTGwgSCulp7Fluc failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 239, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 91, in _call
    raise RuntimeError(error_message)
RuntimeError: UNIQUE constraint failed: setting.code
2018-03-22 15:11:58 22400 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 53 - INFO - Executing post-update migration code for ALBA Node pkjrQqZhltQOw6Ko
2018-03-22 15:11:58 25100 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 54 - ERROR - Executing post-update migration code for ALBA Node pkjrQqZhltQOw6Ko failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 239, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 91, in _call
    raise RuntimeError(error_message)
RuntimeError: UNIQUE constraint failed: setting.code
2018-03-22 15:11:58 25400 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 55 - INFO - Executing post-update migration code for ALBA Node tPDuz6l7i5YF1PBs
2018-03-22 15:11:58 28500 +0100 - LC1SRV0008 - 7339/139961934456576 - update/albamigration.py - migrate_sdm - 56 - ERROR - Executing post-update migration code for ALBA Node tPDuz6l7i5YF1PBs failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 239, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 91, in _call
    raise RuntimeError(error_message)
RuntimeError: UNIQUE constraint failed: setting.code
```

SDM related stack:
```
Mar 22 15:11:58 LC1SRV0002 python[23987]: 2018-03-22 15:11:58 13000 +0100 - LC1SRV0002 - 23987/140139372963584 - flask/decorators.py - new_function - 61 - ERROR - Unexpected exception
Mar 22 15:11:58 LC1SRV0002 python[23987]: Traceback (most recent call last):
Mar 22 15:11:58 LC1SRV0002 python[23987]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/api/decorators.py", line 111, in new_function
Mar 22 15:11:58 LC1SRV0002 python[23987]:     return_data = f(*args, **kwargs)
Mar 22 15:11:58 LC1SRV0002 python[23987]:   File "/opt/asd-manager/source/app/api.py", line 432, in update_execute_migration_code
Mar 22 15:11:58 LC1SRV0002 python[23987]:     SDMUpdateController.execute_migration_code()
Mar 22 15:11:58 LC1SRV0002 python[23987]:   File "/opt/asd-manager/source/controllers/update.py", line 187, in execute_migration_code
Mar 22 15:11:58 LC1SRV0002 python[23987]:     setting.save()
Mar 22 15:11:58 LC1SRV0002 python[23987]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/dal/base.py", line 165, in save
Mar 22 15:11:58 LC1SRV0002 python[23987]:     prop_values)
Mar 22 15:11:58 LC1SRV0002 python[23987]: IntegrityError: UNIQUE constraint failed: setting.code
```

### Package information
```
openvstorage-backend                 1.12.0-dev.1519202962.286a148-1    amd64        OpenvStorage Backend plugin
openvstorage-sdm                     1.12.0-dev.1519203003.69d2f3f-1    amd64        Open vStorage Backend ASD Manager
```

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/alba-asdmanager/pull/326
Packaged in openvstorage-sdm_1.12.0-dev.1524214275.9dc3dcd-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.12.0
Packaged in openvstorage-backend-core_1.12.0-1_amd64.deb
