### ISSUE TITLE
Checkup maintenance agents fails when adding GENERIC nodes

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#580]
```
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]: 2018-04-10 11:53:44 32100 +0000 - ip-172-31-25-22 - 26237/140146623555328 - celery/log.py - log - 7251 - ERROR - Task alba.checkup_maintenance_agents[15596bf6-5e53-451b-832c-132553c9bfb5] ra
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]: Traceback (most recent call last):
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:     R = retval = fun(*args, **kwargs)
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:     return self.run(*args, **kwargs)
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 461, in new_function
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:     output = f(*args, **kwargs)
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 1839, in checkup_maintenance_agents
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:     alba_nodes = sorted(AlbaNodeList.get_albanodes(), key=lambda an: ExtensionsToolbox.advanced_sort(element=an.ip, separator='.'))
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 1839, in <lambda>
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:     alba_nodes = sorted(AlbaNodeList.get_albanodes(), key=lambda an: ExtensionsToolbox.advanced_sort(element=an.ip, separator='.'))
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/toolbox.py", line 202, in advanced_sort
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]:     entries = element.split(separator)
Apr 10 11:53:44 ip-172-31-25-22 celery[26237]: AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/framework-alba-plugin/pull/585
Packaged in openvstorage-backend-core_1.12.0-dev.1524658535.5197e88-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.12.0
Packaged in openvstorage-backend-core_1.12.0-1_amd64.deb
