### ISSUE TITLE
[Bighorn] Unable to retrieve osd statistics of the statsmonkey

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#583]
### Problem description
The statsmonkey can't fetch the osd statistics anymore

Stacktrace:

```
2018-04-25 11:29:40 83300 +0200 - pocops-voldrv01 - 9178/140002369464064 - lib/albastatsmonkey.py - _get_stats_osds_for_alba_backend - 1 - ERROR - Retrieving OSD statistics failed for ALBA Backend hddbackend01
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/albastatsmonkey.py", line 342, in _get_stats_osds_for_alba_backend
    'fields': cls._convert_to_float_values(result),
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/monitoring/statsmonkey.py", line 196, in _convert_to_float_values
    output['_'.join(str(k) for k in path)] = float(json_output[key])
TypeError: float() argument must be a string or a number
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-5-7da2317bbb55> in <module>()
----> 1 AlbaStatsMonkeyController.get_stats_osds()

/opt/OpenvStorage/ovs/lib/albastatsmonkey.pyc in get_stats_osds(cls)
    362 
    363         if len(errors) > 0:
--> 364             raise Exception('Retrieving OSD statistics failed for ALBA Backends:\n * {0}'.format('\n * '.join(errors)))
    365         return False, stats

Exception: Retrieving OSD statistics failed for ALBA Backends:
 * ssdbackend01
 * hddbackend01

```

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework-alba-plugin/pull/584
Packaged in openvstorage-backend-core_1.12.0-dev.1524658535.5197e88-1_amd64.deb

**Comment by wimpers** [comment]
@JeffreyDevloo now we just pop the version value. Can't we just leave it in there f.e. by doing a check if is a float and otherwise store it as a string?

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.12.0
Packaged in openvstorage-backend-core_1.12.0-1_amd64.deb
